### ISSUE TITLE
Cannot leave HELP with EXIT nor F1-key, calculator stuck in HELP menu

### ISSUE THREAD

**Issue by emefff** [zooxo/IV42#2]
Hello,
when I am in the HELP menu, I cannot leave it with EXIT-key or F1 key :-(. Not even auto-turn off helps. What now, is my DM42 bricked? I can only change to the original help file of DM42.
Mario.

**Comment by emefff** [comment]
Ok, somehow I provoked an error with pressing EXIT multiple times and it changed back to the program. Now I can leave the HELP with exit. Weird. Never mind,
Mario.

**Comment by zooxo** [comment]
Hi emefff!

Sorry to hear about your troubles - but good to see that you solved it.
Can you describe more exactly what happened - did you view the iv42help.htm file with the internal browser?

At least it is always possible to reset the DM42 with the reset button (back side).
If you got intense troubles you can press the reset button AND hold the F1-key (till beep). And you are on the OS level (DMCP), where you can format the USB disk or load another program (*.prg). 

This rescued me some times when I really got stuck because of a damaged USB disk, bad USB cable contact or programmed something forbidden at IV42 start.

Finally the OS (DMCP) seems to be very stable (better than Windows ;-) ).

Regards
deetee

**Comment by emefff** [comment]
Hello,
I am afraid, I can't describe it better: when viewing the help file on the DM42, pressing EXIT or F1 did not work for a few minutes. I waited for auto-turn off (after 5min or so) but after turning DM42 on, I was again in the help file. F3 worked, but only changing to another help file (DM42-file or wp34s-file) was possible. I doubt that both buttons F1 and EXIT did not work, that would be an unbelievable coincidence. After a few minutes, I was able to turn off the DM42 with EXIT (or shift EXIT I can't remember). However, after turning it on, I was in the normal screen of IV42 again. The top row showed 'Error'. Since then, I haven't had any trouble but this: when I execute a program named 'NEW1' with the XEQ button, the it seems, the name of this program was changed to 'XEQ' (in the dictionary-view) instead of showing the still valid name (when I enter program mode) 'NEW1'. Thus, I think the problem with menu-mode was maybe just some sort of hiccup. 
I pull my hat to your  projects, IV is also great. Do you know about the wp34s port to DM42?
Mario.
