### ISSUE TITLE
Call user program from within another

### ISSUE THREAD

**Issue by rearman** [zooxo/IV42#4]
Having trouble when calling one user program from within another 
First program is COUN : 2 SWAP PWR 1 - END
Second is VTOC : COUN * SWAP / END (have also tried with an XEQ after COUN)

Calling COUN works as expected, ( 16 -- 65536 ), but VTOC gives me  the NO PROGRAM message.  Is there something else I need to do to use COUN within VTOC?

**Comment by zooxo** [comment]
Hello rearman!

Sorry for the late answer. Unfortunately I sold my IV42 prototype (at a reasonable price) - so I don't have the hardware to test.

Actually there shouldn't be a problem if one user program calls another.
 
Due to the code of IV42 the "no program" message occurs if the program couldn't be found when the maximum of user programs (18) was reached. Do you have 16 other user programs?

Regards
deetee

**Comment by rearman** [comment]
No, those are the only two programs.
It works if I put VTOC in the first (top left) slot, and COUN in the second, but not the other way around...guess I need to start thinking more forth-y and work from the bottom right up!
